#!/bin/sh

#
# chkconfig: - 86 14
# description: control all tomcat instances
#
# $Id: tomcat 3600 2011-10-06 00:37:34Z mheiges $
# $URL: https://mango.ctegd.uga.edu/svn/ApiCommonSystem/trunk/Tomcat/bin/tomcat $
#

TOMCAT_INSTANCES_DIR=/usr/local/tomcat_instances
MANAGER=/usr/bin/instance_manager
cd $TOMCAT_INSTANCES_DIR

this=`basename $0`

if [ ! -x ${MANAGER} ]; then
 echo "'${MANAGER}' not found or permissions not valid"
 exit 1
fi

instances=`${MANAGER} list`
if [[ $? -ne 0 ]]; then
  echo "Failed to run '${MANAGER} list'. Unable to continue."
  exit 1
fi

start() {
    if test `id -u` != 0; then 
        echo 'root permissions required'; exit 4;
    fi
    for instance in ${instances[@]}; do
        ${MANAGER} start $instance
    done
}

stop() {
    if test `id -u` != 0; then 
        echo 'root permissions required'; exit 4;
    fi
    for instance in ${instances[@]}; do
        ${MANAGER} stop $instance
    done
}

case "$1" in
  start)
    start
    exit $?
    ;;

  stop)
    stop
    exit $?
    ;;

  restart)
    stop
    start
    exit $?
    ;;

  status)
    ${MANAGER} status
    ;;
  *)
    echo "usage: $this {start|stop|restart|status}"
    ;;
esac    
